import json

# Your original JSON data (as a string or loaded from a file)
original_data = [
{"query":"What is the primary focus of EIE-II Module 1?","ground_truth":"The primary focus of EIE-II Module 1 is **Why Startups Fail and What You Can Do About It**. It introduces common startup challenges and failure points, emphasizing the importance of focusing on customers and markets from the start, and begins to introduce methodologies like the Lean Startup Method to address these issues."},
{"query":"What is the overall goal of the Essentials of Innovation & Entrepreneurship (EIE) program?","ground_truth":"The overall goal of the Essentials of Innovation & Entrepreneurship (EIE) program is to **prepare students for and kickstart their Innovation & Entrepreneurship (I&E) journey**.\n\nThis involves:\n*   Helping them discover their \"True North,\" interests, and passion.\n*   Enabling them to identify and pursue ideas\/opportunities (tech, business, startup, research).\n*   Facilitating the finding of collaborators, teammates, and potential co-founders.\n*   Providing support (funding, prototyping, mentoring) to build out their ideas and teams.\n*   Equipping them with tech, business, and soft skills, including applying principles like Lean Startup and Customer Development to safely create startups and solve real-world problems.\n*   Offering a platform (like CIE Ignite) to apply their I&E skills and gain exposure to the startup ecosystem."},
{"query":"Who is the Lead Instructor for CIE@RR, and what is their contact email?","ground_truth":"The Lead Instructor for CIE@RR is **Prof. Sathya Prasad**, and their contact email is **sathya.prasad@pes.edu**."},
{"query":"Who is the CIE Program Manager, and how can students contact them for course-related assistance?","ground_truth":"The CIE Program Manager is **Mr. Madhukar Narasimha**.\n\nStudents can contact him for course-related assistance by reaching out to **cieoffice@pes.edu**."},
{"query":"Who are the EIE Teaching Assistants for EIE-II?","ground_truth":"The EIE Teaching Assistants (TA) for EIE-II are:\n\n*   Chirag C\n*   Shekar Arpan Mascarenhas\n*   Dhruv Tandon\n*   Ajay Rao\n*   Chinmay D"},
{"query":"What is the core vision behind the EIE course, beyond being just a course?","ground_truth":"The core vision behind the EIE course, beyond being just a traditional course, is to be a platform that helps students:\n\n*   **Discover their 'True North,' interests, or passion.**\n*   **Identify ideas and opportunities** they consider worth pursuing (whether in tech, business, startups, or research).\n*   **Find potential collaborators, teammates, startup founders, or innovators.**\n*   **Receive support** for funding, prototyping, and mentoring to build out their ideas and teams."},
{"query":"How does EIE help students discover their 'True North' or passions?","ground_truth":"EIE (Essentials of Innovation & Entrepreneurship) helps students discover their 'True North' or passions by:\n\n*   **Explicitly stating it as a core vision:** The EIE-I course is envisioned to help students \"Discover your \u2018True North\u2019 \/ Interests \/ Passion.\"\n*   **Encouraging idea identification:** It guides students to \"Identify ideas\/opportunities that you consider worth pursuing (tech \/ biz \/ startup \/ research \/ etc).\"\n*   **Developing skills:** It helps students \"Build Tech, Business and Soft skills; Discover their \u2018True North\u2019\/passion, Teammates and more."},
{"query":"What kind of ideas or opportunities are students encouraged to identify and pursue in EIE?","ground_truth":"In EIE, students are encouraged to identify and pursue **ideas or opportunities that they consider worth pursuing**.\n\nThese opportunities can span various fields, including:\n*   **Tech** (Technology)\n*   **Biz** (Business)\n*   **Startup**\n*   **Research**\n*   More broadly, they are encouraged to create a startup by picking a **real-world problem (opportunity) and solving it** using proven principles."},
{"query":"What types of support (e.g., funding, prototyping, mentoring) are available for students to build out their ideas?","ground_truth":"Based on the provided material, students have access to the following types of support to build out their ideas:\n\n*   **Funding:** This includes direct \"funding\" and \"grants\" (e.g., through the CIE PESU -IITx Co-Innovation-Center).\n*   **Prototyping:** Support for \"prototyping\" is available, including the ability to \"build prototype\/minimum-viable-product\" and access to the \"CIE Makerspace\" for building prototypes.\n*   **Mentoring:** Students can receive \"mentoring\" from general sources and specifically \"mentorship from CIE Industry Mentors\" for their team projects.\n\nAdditionally, the program helps students discover potential collaborators\/teammates and build essential tech, business, and soft skills."},
{"query":"How does EIE-II build upon the concepts and learnings from EIE-I?","ground_truth":"EIE-II directly builds upon the concepts and learnings from EIE-I by shifting from foundational discovery and ideation to the practical application of those principles.\n\nSpecifically:\n*   **Application of Learned Concepts:** EIE-II's core objective is **\"Applying what you learned in EIE-1 (BMC, Design Thinking, etc).\"** This means taking the theoretical knowledge and frameworks introduced in EIE-I (like the Business Model Canvas and Design Thinking) and putting them into practice.\n*   **Transition from Idea to Startup Creation:** While EIE-I focuses on helping students \"Discover your \u2018True North\u2019 \/ Interests \/ Passion,\" \"Identify ideas\/opportunities,\" and \"Find potential collaborators,\" EIE-II provides the opportunity to **\"safely create a startup\"** by picking a real-world problem and solving it using proven principles.\n*   **Validation and Execution:** EIE-II introduces and utilizes methodologies like **Lean Startup and Customer Development principles** for ideas, moving towards \"Evidence-based\" versus \"faith-based\" entrepreneurship. This builds on the initial idea identification from EIE-I by guiding students through the process of validating those ideas in the market.\n*   **Continued Team Building:** EIE-II continues the emphasis on team formation by encouraging students to \"Discover great teammates \u2013potential\/future Co-Founders!\" building on the initial search for collaborators in EIE-I."},
{"query":"What is the primary focus of EIE-II Module 1?","ground_truth":"The primary focus of EIE-II Module 1 is **Why Startups Fail and What You Can Do About It**. It introduces common startup challenges and failure points, emphasizing the importance of focusing on customers and markets from the start, and begins to introduce methodologies like the Lean Startup Method to address these issues."},
{"query":"What is the overall goal of the Essentials of Innovation & Entrepreneurship (EIE) program?","ground_truth":"The overall goal of the Essentials of Innovation & Entrepreneurship (EIE) program is to **prepare students for and kickstart their Innovation & Entrepreneurship (I&E) journey**.\n\nThis involves:\n*   Helping them discover their \"True North,\" interests, and passion.\n*   Enabling them to identify and pursue ideas\/opportunities (tech, business, startup, research).\n*   Facilitating the finding of collaborators, teammates, and potential co-founders.\n*   Providing support (funding, prototyping, mentoring) to build out their ideas and teams.\n*   Equipping them with tech, business, and soft skills, including applying principles like Lean Startup and Customer Development to safely create startups and solve real-world problems.\n*   Offering a platform (like CIE Ignite) to apply their I&E skills and gain exposure to the startup ecosystem."},
{"query":"Who is the Lead Instructor for CIE@RR, and what is their contact email?","ground_truth":"The Lead Instructor for CIE@RR is **Prof. Sathya Prasad**, and their contact email is **sathya.prasad@pes.edu**."},
{"query":"Who is the CIE Program Manager, and how can students contact them for course-related assistance?","ground_truth":"The CIE Program Manager is **Mr. Madhukar Narasimha**.\n\nStudents can contact him for course-related assistance by reaching out to **cieoffice@pes.edu**."},
{"query":"Who are the EIE Teaching Assistants for EIE-II?","ground_truth":"The EIE Teaching Assistants (TA) for EIE-II are:\n\n*   Chirag C\n*   Shekar Arpan Mascarenhas\n*   Dhruv Tandon\n*   Ajay Rao\n*   Chinmay D"},
{"query":"What is the core vision behind the EIE course, beyond being just a course?","ground_truth":"The core vision behind the EIE course, beyond being just a traditional course, is to be a platform that helps students:\n\n*   **Discover their 'True North,' interests, or passion.**\n*   **Identify ideas and opportunities** they consider worth pursuing (whether in tech, business, startups, or research).\n*   **Find potential collaborators, teammates, startup founders, or innovators.**\n*   **Receive support** for funding, prototyping, and mentoring to build out their ideas and teams."},
{"query":"How does EIE help students discover their 'True North' or passions?","ground_truth":"EIE (Essentials of Innovation & Entrepreneurship) helps students discover their 'True North' or passions by:\n\n*   **Explicitly stating it as a core vision:** The EIE-I course is envisioned to help students \"Discover your \u2018True North\u2019 \/ Interests \/ Passion.\"\n*   **Encouraging idea identification:** It guides students to \"Identify ideas\/opportunities that you consider worth pursuing (tech \/ biz \/ startup \/ research \/ etc).\"\n*   **Developing skills:** It helps students \"Build Tech, Business and Soft skills; Discover their \u2018True North\u2019\/passion, Teammates and more."},
{"query":"What kind of ideas or opportunities are students encouraged to identify and pursue in EIE?","ground_truth":"In EIE, students are encouraged to identify and pursue **ideas or opportunities that they consider worth pursuing**.\n\nThese opportunities can span various fields, including:\n*   **Tech** (Technology)\n*   **Biz** (Business)\n*   **Startup**\n*   **Research**\n*   More broadly, they are encouraged to create a startup by picking a **real-world problem (opportunity) and solving it** using proven principles."},
{"query":"What types of support (e.g., funding, prototyping, mentoring) are available for students to build out their ideas?","ground_truth":"Based on the provided material, students have access to the following types of support to build out their ideas:\n\n*   **Funding:** This includes direct \"funding\" and \"grants\" (e.g., through the CIE PESU -IITx Co-Innovation-Center).\n*   **Prototyping:** Support for \"prototyping\" is available, including the ability to \"build prototype\/minimum-viable-product\" and access to the \"CIE Makerspace\" for building prototypes.\n*   **Mentoring:** Students can receive \"mentoring\" from general sources and specifically \"mentorship from CIE Industry Mentors\" for their team projects.\n\nAdditionally, the program helps students discover potential collaborators\/teammates and build essential tech, business, and soft skills."},
{"query":"How does EIE-II build upon the concepts and learnings from EIE-I?","ground_truth":"EIE-II directly builds upon the concepts and learnings from EIE-I by shifting from foundational discovery and ideation to the practical application of those principles.\n\nSpecifically:\n*   **Application of Learned Concepts:** EIE-II's core objective is **\"Applying what you learned in EIE-1 (BMC, Design Thinking, etc).\"** This means taking the theoretical knowledge and frameworks introduced in EIE-I (like the Business Model Canvas and Design Thinking) and putting them into practice.\n*   **Transition from Idea to Startup Creation:** While EIE-I focuses on helping students \"Discover your \u2018True North\u2019 \/ Interests \/ Passion,\" \"Identify ideas\/opportunities,\" and \"Find potential collaborators,\" EIE-II provides the opportunity to **\"safely create a startup\"** by picking a real-world problem and solving it using proven principles.\n*   **Validation and Execution:** EIE-II introduces and utilizes methodologies like **Lean Startup and Customer Development principles** for ideas, moving towards \"Evidence-based\" versus \"faith-based\" entrepreneurship. This builds on the initial idea identification from EIE-I by guiding students through the process of validating those ideas in the market.\n*   **Continued Team Building:** EIE-II continues the emphasis on team formation by encouraging students to \"Discover great teammates \u2013potential\/future Co-Founders!\" building on the initial search for collaborators in EIE-I."},
{"query":"Can EIE lead to internship opportunities like CIE\/CoE Internships?","ground_truth":"Yes, EIE (Essentials of Innovation & Entrepreneurship) can lead to internship opportunities like CIE\/CoE Internships.\n\nThe provided material states under \"EIE -II How to Get the Best Out of this Course?\":\n*   \"Based on your efforts\/results, apply for CIE Summer Internship\"\n\nAdditionally, the \"How Can EIE Help You in Your Education\/Career?\" section illustrates a sample path where EIE-I and EIE-II are followed by \"CIE \/ CoE Internship\" opportunities in the summer semesters."},
{"query":"What skills will students build through the EIE-II course?","ground_truth":"Through the EIE-II course, students will build a variety of skills, including:\n\n*   **Tech, Business, and Soft skills**\n*   **Innovation & Entrepreneurship (I&E) skills**, including applying what they learned in EIE-1 (such as Business Model Canvas and Design Thinking)\n*   **Startup Creation skills**, by picking real-world problems and solving them using proven principles\n*   **Lean Startup and Customer Development principles** application skills\n*   **Evidence-based entrepreneurship** (vs. faith-based)\n*   **Teamwork and collaboration skills** (discovering and working with teammates\/potential co-founders)\n*   **Prototyping skills** (building prototypes\/minimum-viable-products)\n*   **Validation skills** for ideas\/products\n*   **Business acumen**\n*   **Interviewing skills** (specifically in Customer Discovery)\n*   **Hypothesis building skills** (testable\/measurable)\n*   **Startup Finance and Marketing fundamentals**\n*   **Digital Business Models and Digital Marketing** (including use of GenAI for innovation)\n*   **Startup Pitching skills**\n*   **Developing an Entrepreneurial Action Plan**"},
{"query":"What platform does EIE-II provide for applying innovation and entrepreneurship skills?","ground_truth":"EIE-II provides **CIE Ignite** as a platform to apply innovation and entrepreneurship skills."},
{"query":"Will students have exposure to transformative technology-driven innovations in EIE-II?","ground_truth":"Yes, according to the EIE-II Course Objectives, students will have \"Exposure to transformative technology-driven innovations.\""},
{"query":"What are the main objectives of the EIE-II course?","ground_truth":"The main objectives of the EIE-II course are:\n\n*   To provide a fun way to prepare students for an exciting and impactful 3rd\/4th year journey at PESU.\n*   To enable students to apply what they learned in EIE-I (such as Business Model Canvas, Design Thinking, etc.).\n*   To offer an opportunity for students to safely create a startup by picking a real-world problem (opportunity) and solving it using proven principles.\n*   To teach students how to use Lean Startup and Customer Development principles for their ideas.\n*   To promote \"Evidence-based\" entrepreneurship over \"faith-based\" entrepreneurship.\n*   To help students discover great teammates who could be potential future Co-Founders."},
{"query":"How does EIE-II offer an opportunity for students to safely create a startup?","ground_truth":"EIE-II offers students the opportunity to safely create a startup by:\n\n1.  **Applying Proven Principles:** Students learn and apply established methodologies like Lean Startup and Customer Development. This emphasizes \"evidence-based\" entrepreneurship over \"faith-based,\" encouraging validation of ideas through customer discovery before significant investment.\n2.  **Focusing on Real-World Problems:** The course guides students in identifying and solving real-world problems or opportunities, providing a practical foundation for their startup.\n3.  **Providing Mentorship and Resources:** Students can leverage mentorship from CIE Industry Mentors for their team projects and utilize resources like the CIE Makerspace to build prototypes.\n4.  **Structured Application:** The course provides a platform, CIE Ignite, to apply their innovation and entrepreneurship skills in a structured environment."},
{"query":"Which proven principles are students encouraged to use for solving real-world problems in EIE-II?","ground_truth":"In EIE-II, students are encouraged to use **Lean Startup & Customer Development principles** for solving real-world problems."},
{"query":"What is the difference between \"evidence-based\" and \"faith-based\" entrepreneurship as taught in this course?","ground_truth":"Based on the provided material, the difference between \"evidence-based\" and \"faith-based\" entrepreneurship in this course can be understood as follows:\n\n*   **\"Faith-based\" entrepreneurship** aligns with the **Conventional Approach \/ Product Development Model**. This approach operates on the \"BIG assumption: Customers + Market available\/ready\" and involves building a business plan and the product first, often driven by technology, before fully validating the market need or customer interest. It's based on the entrepreneur's belief or assumption that their product will find a market, rather than validated evidence. The course implies this often leads to failure due to a lack of customers.\n\n*   **\"Evidence-based\" entrepreneurship** aligns with the **Lean Startup Method**. This approach emphasizes focusing on \"Customers and Markets from \u2018Day 0\u2019\" through **Customer Development**. It seeks to prevent failure by validating ideas and assumptions with real-world evidence and feedback from potential customers, rather than relying on internal assumptions. This method involves testing hypotheses and adapting based on what is learned from the market."},
{"query":"How does the course help students find potential co-founders?","ground_truth":"The course, \"Essentials of Innovation & Entrepreneurship (EIE)\", helps students find potential co-founders in the following ways:\n\n*   **Explicit Objective:** One of the core aims of EIE-I is to help students \"Find potential collaborators \/ teammates \/ startup founders \/ innovators.\"\n*   **Learning Outcome:** A stated learning outcome for EIE-II is to \"Discover great teammates \u2013 potential\/future Co-Founders!\"\n*   **Team-Based Learning:** The course encourages \"Lots of \u2018doing\u2019 in a Team setting,\" providing practical opportunities for students to identify and work with potential co-founders."},
{"query":"How are the learnings from EIE expected to be applied with other courses or projects?","ground_truth":"The learnings from EIE (Essentials of Innovation & Entrepreneurship) are expected to be applied in other courses, projects, or gigs in the following ways:\n\n*   **Applying EIE-1 Concepts:** Students will apply principles learned in EIE-1, such as Business Model Canvas (BMC) and Design Thinking.\n*   **Startup Creation:** The course provides an opportunity to safely create a startup by identifying and solving real-world problems using proven entrepreneurial principles.\n*   **Lean Startup & Customer Development:** Students will utilize Lean Startup and Customer Development principles for their ideas.\n*   **Evidence-Based Entrepreneurship:** The course promotes an \"evidence-based\" approach to entrepreneurship over a \"faith-based\" one.\n*   **Team Formation:** It helps in discovering potential teammates who could become future co-founders."},
{"query":"What are the key themes or topics covered in the EIE-II course outline?","ground_truth":"The EIE-II course outline covers the following key themes and topics:\n\n*   **Introduction to Startup Challenges\/Failure:** Understanding why startups fail and what actions can be taken to prevent it.\n*   **Customer Discovery (CD):** In-depth exploration of why, what, and how to conduct customer discovery, including interviewing skills and building testable\/measurable hypotheses.\n*   **Startup Finance Fundamentals II:** Advanced principles of startup finance.\n*   **Startup Marketing Fundamentals II:** Advanced principles of startup marketing.\n*   **Digital Business Models:** Understanding various digital business models.\n*   **Digital Marketing and use of GenAI for Innovation:** Applying digital marketing strategies and leveraging Generative AI for innovation.\n*   **Startup Pitching II:** Developing and refining startup pitching skills.\n*   **Startup Legal Fundamentals:** Basic legal aspects relevant to startups.\n*   **Developing your Entrepreneurial Action Plan:** Creating a practical plan for entrepreneurial endeavors."},
{"query":"What are the \"CIE-Ignite Milestones\" mentioned in the course outline, and how do they relate to the themes?","ground_truth":"The \"CIE-Ignite Milestones\" are distinct stages (Stage0 (S0), Stage1 (S1), Stage2 (S2), and Stage3 (S3)) outlined within the EIE-II course curriculum.\n\nHere's how they relate to the course themes:\n\n*   **CIE-Ignite Milestones** serve as integration points or checkpoints within the course, grouping related themes and topics together. They appear to represent a progression in the startup development process that the course aims to teach.\n*   **Relationship to Themes:**\n    *   **Stage0 (S0):** Corresponds to foundational themes focused on **Introduction to Startup Challenges\/Failure** and in-depth **Customer Discovery** (Why\/What\/How, Interviewing Skills, Building Testable\/Measurable Hypotheses, Best Practices).\n    *   **Stage1 (S1):** Aligns with themes covering **Startup Finance Fundamentals II** and **Startup Marketing Fundamentals II**.\n    *   **Stage2 (S2):** Relates to themes on **Digital Business Models** and the application of **Digital Marketing and GenAI for Innovation**.\n    *   **Stage3 (S3):** Encompasses themes dedicated to **Startup Pitching II**, **Startup Legal Fundamentals**, and **Developing your Entrepreneurial Action Plan**.\n\nIn a broader sense, \"CIE-Ignite\" is mentioned as a platform where students can **apply their Innovation & Entrepreneurship (I&E) skills** and practice the frameworks and tools learned in the course. It's also a component of the course assessment, accounting for 10% of the total grade."},
{"query":"Which modules are primarily dedicated to Customer Discovery (CD) skills?","ground_truth":"Based on the provided EIE -II Course Outline, the modules primarily dedicated to Customer Discovery (CD) skills are:\n\n*   **M2 Customer Discovery (CD) \u2013 Why\/What\/How**\n*   **M3 CD Deep-dive: Interviewing Skills**\n*   **M4 CD Deep-dive: Build your Testable\/Measurable Hypotheses**\n*   **M5 CD Deep-dive: Best practices**"},
{"query":"When are Startup Finance Fundamentals covered in the course outline?","ground_truth":"According to the \"EIE -II Course Outline*\", Startup Finance Fundamentals are covered in **Module 6 (M6)**."},
{"query":"What is the topic of Module 9 concerning marketing and innovation?","ground_truth":"The topic of Module 9 concerning marketing and innovation is **Digital Marketing and use of GenAI for Innovation**."},
{"query":"What legal aspects of startups are covered in the course?","ground_truth":"The course covers \"Startup Legal Fundamentals\" as part of its curriculum, specifically in Module 11 (M11) of the \"EIE -II Course Outline.\""},
{"query":"Is the EIE-II course outline final, or is it subject to modification?","ground_truth":"Based on the provided material, the EIE-II course outline is **proposed** and **subject to modification**."},
{"query":"How many credits is the EIE-II course worth?","ground_truth":"The EIE-II course is worth **2 Credits**."},
{"query":"What is the weekly time commitment (in hours) for the EIE-II course?","ground_truth":"The weekly time commitment for the EIE-II course is **2 hours**."},
{"query":"Will all EIE-II sessions be online, or will there be in-person sessions?","ground_truth":"Based on the provided material, EIE-II sessions will be **mostly online**, but **some sessions will be in-person (F2F) with advance notice**."},
{"query":"Who are the typical guest speakers invited to give talks during EIE-II sessions?","ground_truth":"During EIE-II sessions, typical guest speakers invited to give talks include **Startup Founders, Industry Experts, and PESU Faculty**."},
{"query":"What is the grading scale used for EIE-II (e.g., S, A, B, C, D, E, F percentages)?","ground_truth":"Based on the provided material, the grading scale used for EIE-II is as follows:\n\n*   **S:** 90 \u2013 100%\n*   **A:** 80 \u2013 89%\n*   **B:** 70 \u2013 79%\n*   **C:** 60 \u2013 69%\n*   **D:** 50 \u2013 59%\n*   **E:** 40 \u2013 49%\n*   **F:** 39% & below"},
{"query":"What are the different assessment components (e.g., CIE Ignite\/ideathon, CBT, ESA) and their respective weightages in EIE-II?","ground_truth":"In EIE-II, the assessment components and their respective weightages are as follows:\n\n*   **CIE Ignite\/ideathon:** 10%\n*   **CBT-2 ISAs:** 20% each (implying two such assessments, totaling 40%)\n*   **1 ESA:** 50%"},
{"query":"What is the minimum attendance requirement for the course?","ground_truth":"The minimum attendance requirement for the course is 75%+, which is the same as the university requirements."},
{"query":"What are the recommended references or resources for the EIE-II course?","ground_truth":"For the EIE-II course, the recommended references and resources include:\n\n**General References:**\n*   **Books\/Courses:**\n    *   *Technology Ventures: From Idea to Enterprise*, McGraw Hill\n    *   PES University \u2018CIE Level 1\u2019 Course - *Getting Started With Entrepreneurship*\n    *   VentureLab (Entrepreneurial Skillset and Mindset)\n    *   European Union (EU) Entrepreneurship Competencies\n\n**Specific Required\/Recommended Reading\/Viewing (primarily on Lean Startup Method):**\n*   **Required:**\n    *   \"The Lean Approach \u2013Introduction\" (Steve Blank, 1:05 mins) - https://youtu.be/vyR1JjS1Duc\n    *   \"The Lean Method\" (Steve Blank, 5:20 mins) - https://youtu.be/GPQExuB-lWw\n    *   \"Customer vs Product Development - How to Build a Startup\" (Steve Blank) - https://www.youtube.com/watch?v=f_LNNnNfpp4&feature=youtu.be\n    *   \"Why the Lean Startup Changes Everything\" (Harvard Business Review Article, 9 mins) - https://hbr.org/video/5712986167001/why-the-Lean-startup-changes-everything\n*   **Recommended:**\n    *   \"Cracking the Code: Link\" (Kauffman Sketchbook)\n    *   \"Visionaries: Link\" (Kauffman Sketchbook)"},
{"query":"What are the key ingredients for a successful entrepreneur highlighted in the course?","ground_truth":"The course highlights the following as key ingredients for a successful entrepreneur:\n\n*   **Discipline**\n*   **Perseverance**\n*   **Commitment**"},
{"query":"How can students leverage CIE-Ignite to get the best out of this course?","ground_truth":"Students can leverage CIE-Ignite to get the best out of the course primarily by **practicing the frameworks and tools** learned.\n\nCIE-Ignite serves as a platform to apply their Innovation and Entrepreneurship (I&E) skills, with specific milestones integrated into the course outline (Stage 0, Stage 1, Stage 2, Stage 3). This hands-on application in a team setting is crucial for developing skills and discovering what works best for them."},
{"query":"What resources are available for building prototypes for team projects?","ground_truth":"Based on the provided material, the following resources are available for building prototypes for team projects:\n\n*   **Prototyping support** is available as part of the EIE program to help build out ideas\/teams.\n*   The **CIE Makerspace** can be used to build prototypes."},
{"query":"How is attendance recorded for online sessions, especially regarding quizzes?","ground_truth":"For online sessions, attendance is recorded via the **Session Quiz on PESU Academy**."},
{"query":"What is Steve Blank's definition of a startup, as presented in the material?","ground_truth":"According to the provided material, Steve Blank defines a startup as:\n\n\"**A temporary organization designed to search for a repeatable and scalable business model.**\""},
{"query":"When are Startup Finance Fundamentals covered in the course outline?","ground_truth":"According to the \"EIE -II Course Outline*\", Startup Finance Fundamentals are covered in **Module 6 (M6)**."},
{"query":"What is the topic of Module 9 concerning marketing and innovation?","ground_truth":"The topic of Module 9 concerning marketing and innovation is **Digital Marketing and use of GenAI for Innovation**."},
{"query":"What legal aspects of startups are covered in the course?","ground_truth":"The course covers \"Startup Legal Fundamentals\" as part of its curriculum, specifically in Module 11 (M11) of the \"EIE -II Course Outline.\""},
{"query":"Is the EIE-II course outline final, or is it subject to modification?","ground_truth":"Based on the provided material, the EIE-II course outline is **proposed** and **subject to modification**."},
{"query":"How many credits is the EIE-II course worth?","ground_truth":"The EIE-II course is worth **2 Credits**."},
{"query":"What is the weekly time commitment (in hours) for the EIE-II course?","ground_truth":"The weekly time commitment for the EIE-II course is **2 hours**."},
{"query":"Will all EIE-II sessions be online, or will there be in-person sessions?","ground_truth":"Based on the provided material, EIE-II sessions will be **mostly online**, but **some sessions will be in-person (F2F) with advance notice**."},
{"query":"Who are the typical guest speakers invited to give talks during EIE-II sessions?","ground_truth":"During EIE-II sessions, typical guest speakers invited to give talks include **Startup Founders, Industry Experts, and PESU Faculty**."},
{"query":"What is the grading scale used for EIE-II (e.g., S, A, B, C, D, E, F percentages)?","ground_truth":"Based on the provided material, the grading scale used for EIE-II is as follows:\n\n*   **S:** 90 \u2013 100%\n*   **A:** 80 \u2013 89%\n*   **B:** 70 \u2013 79%\n*   **C:** 60 \u2013 69%\n*   **D:** 50 \u2013 59%\n*   **E:** 40 \u2013 49%\n*   **F:** 39% & below"},
{"query":"What are the different assessment components (e.g., CIE Ignite\/ideathon, CBT, ESA) and their respective weightages in EIE-II?","ground_truth":"In EIE-II, the assessment components and their respective weightages are as follows:\n\n*   **CIE Ignite\/ideathon:** 10%\n*   **CBT-2 ISAs:** 20% each (implying two such assessments, totaling 40%)\n*   **1 ESA:** 50%"},
{"query":"What is the minimum attendance requirement for the course?","ground_truth":"The minimum attendance requirement for the course is 75%+, which is the same as the university requirements."},
{"query":"What are the recommended references or resources for the EIE-II course?","ground_truth":"For the EIE-II course, the recommended references and resources include:\n\n**General References:**\n*   **Books\/Courses:**\n    *   *Technology Ventures: From Idea to Enterprise*, McGraw Hill\n    *   PES University \u2018CIE Level 1\u2019 Course - *Getting Started With Entrepreneurship*\n    *   VentureLab (Entrepreneurial Skillset and Mindset)\n    *   European Union (EU) Entrepreneurship Competencies\n\n**Specific Required\/Recommended Reading\/Viewing (primarily on Lean Startup Method):**\n*   **Required:**\n    *   \"The Lean Approach \u2013Introduction\" (Steve Blank, 1:05 mins) - https:\/\/youtu.be\/vyR1JjS1Duc\n    *   \"The Lean Method\" (Steve Blank, 5:20 mins) - https:\/\/youtu.be\/GPQExuB-lWw\n    *   \"Customer vs Product Development - How to Build a Startup\" (Steve Blank) - https:\/\/www.youtube.com\/watch?v=f_LNNnNfpp4&feature=youtu.be\n    *   \"Why the Lean Startup Changes Everything\" (Harvard Business Review Article, 9 mins) - https:\/\/hbr.org\/video\/5712986167001\/why-the-Lean-startup-changes-everything\n*   **Recommended:**\n    *   \"Cracking the Code: Link\" (Kauffman Sketchbook)\n    *   \"Visionaries: Link\" (Kauffman Sketchbook)"},
{"query":"What are the key ingredients for a successful entrepreneur highlighted in the course?","ground_truth":"The course highlights the following as key ingredients for a successful entrepreneur:\n\n*   **Discipline**\n*   **Perseverance**\n*   **Commitment**"},
{"query":"How can students leverage CIE-Ignite to get the best out of this course?","ground_truth":"Students can leverage CIE-Ignite to get the best out of the course primarily by **practicing the frameworks and tools** learned.\n\nCIE-Ignite serves as a platform to apply their Innovation and Entrepreneurship (I&E) skills, with specific milestones integrated into the course outline (Stage 0, Stage 1, Stage 2, Stage 3). This hands-on application in a team setting is crucial for developing skills and discovering what works best for them."},
{"query":"What resources are available for building prototypes for team projects?","ground_truth":"Based on the provided material, the following resources are available for building prototypes for team projects:\n\n*   **Prototyping support** is available as part of the EIE program to help build out ideas\/teams.\n*   The **CIE Makerspace** can be used to build prototypes."},
{"query":"How is attendance recorded for online sessions, especially regarding quizzes?","ground_truth":"For online sessions, attendance is recorded via the **Session Quiz on PESU Academy**."},
{"query":"What is Steve Blank's definition of a startup, as presented in the material?","ground_truth":"According to the provided material, Steve Blank defines a startup as:\n\n\"**A temporary organization designed to search for a repeatable and scalable business model.**\""}

]

# Extract only the queries
query_list = [{"query": item["query"]} for item in original_data]

# Save to a new JSON file
with open("queries_only.json", "w", encoding="utf-8") as f:
    json.dump(query_list, f, indent=2, ensure_ascii=False)

print("queries_only.json file created successfully.")
